// Code generated by "stringer -type=ScheduleType"; DO NOT EDIT

package schedules

import "fmt"

const _ScheduleType_name = "None"

var _ScheduleType_index = [...]uint8{0, 4}

func (i ScheduleType) String() string {
	if i < 0 || i >= ScheduleType(len(_ScheduleType_index)-1) {
		return fmt.Sprintf("ScheduleType(%d)", i)
	}
	return _ScheduleType_name[_ScheduleType_index[i]:_ScheduleType_index[i+1]]
}
